services:
  - type: web
    name: hillcountryspots
    env: node
    plan: free
    buildCommand: npm install && vite build && esbuild server/production.ts --platform=node --packages=external --bundle --format=esm --outdir=dist --outfile=dist/server.js
    startCommand: NODE_ENV=production node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: "--max-old-space-size=512"
    healthCheckPath: /health